apiVersion: "{{ api_version_virtual_machine }}"
kind: VirtualMachine
metadata:
  annotations:
{% if template.networks is defined and template.networks|length > 0 %}
    k8s.v1.cni.cncf.io/networks: "{{ template.networks | map(attribute='name') | join(', ') }}"
{% endif %}
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
  name: {{ template.name }}
  generation: 2
  namespace: '{{ target_namespace }}'
  labels:
    app: {{ template.name }}
    app_name: {{ template.app_name }}
    role: {{ template.role }}
{% if template.template is defined %}
    vm.kubevirt.io/template: {{ template.template }}
    vm.kubevirt.io/template-namespace: {{ template_namespace }}
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v{{ rhel_os_template_version }}
{% endif %}
    workload.template.kubevirt.io/server: 'true'
    os.family: {{ vm_os_type }}
spec:
  dataVolumeTemplates:
    - apiVersion: {{ api_version_dv }}
      kind: DataVolume
      metadata:
        name: {{ template.name }}-disk0
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
      spec:
        source:
{% if template.template is defined %}
          pvc:
            namespace: {{ template_namespace }}
            name: {{ dv_template_disk_info.resources[0].metadata.name }}
{% else %}
          blank: {}
{% endif %}
        storage:
          resources:
            requests:
              storage: {{ (template.disks[0].size | default(dv_template_disk_info.resources[0].spec.storage.resources.requests.storage)) | replace('GiB', 'Gi') }}
          storageClassName: {{ pvc_storage_class }}
      status: {}
  runStrategy: Manual
  running: null
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: debian12
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: {{ template.name }}
        kubevirt.io/size: medium
        vm.kubevirt.io/name: {{ template.name }}
        app: {{ template.name }}
        app_name: {{ template.app_name }}
        role: {{ template.role }}
    spec:
      domain:
        cpu:
          sockets: {{ template.cpu }}
{% if template.cores is defined %}
          cores: {{ template.cores }}
{% endif %}
{% if template.threads is defined %}
          threads: {{ template.threads }}
{% endif %}
{% if template.cpu_model is defined and template.cpu_model == 'host-passthrough' %}
          model: {{ template.cpu_model }}
{% endif %}
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: {{ template.boot_disk_bus | default('virtio') }}
              name: disk0
{% if boot_iso_pvc_name is defined and boot_iso_pvc_name|length > 0 %}
            - bootOrder: 2
              cdrom:
                bus: sata
              name: boot-iso
{% else %}
            - name: cloudinitdisk
              bootOrder: 3
              cdrom:
                bus: sata
                readonly: true
{% endif %}
          interfaces:
{% if template.networks is defined and template.networks|length > 0 %}
{% for network in template.networks %}
            - bridge: {}
              model: {{ network.model | default('virtio') }}
              name: nic{{ (loop.index-1)|string }}
{% endfor %}
{% else %}
            - bootOrder: 2
              bridge: {}
              model: virtio
              name: nic0
{% endif %}
{% if (template.efi is defined and template.efi|bool) or bootloader_efi is defined %}
        firmware:
          bootloader:
{% if bootloader_efi is defined %}
            efi: {{ bootloader_efi }}
{% else %}
            efi: {}
{% endif %}
        features:
          smm:
            enabled: true
{% endif %}
        machine:
          type: ''
        resources:
          requests:
            memory: {{ ((template.memory|int) * kubevirt_memory_overcommit_ratio) | int | string }}Mi
        memory:
          guest: {{ template.memory }}Mi
      evictionStrategy: LiveMigrate
      hostname: {{ template.name }}
      networks:
{% if template.networks is defined and template.networks|length > 0 %}
{% for network in template.networks %}
        - multus:
            networkName: {{ network.name }}
          name: nic{{ (loop.index-1)|string }}
{% endfor %}
{% else %}
        - name: nic0
          pod: {}
{% endif %}
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
            name: {{ template.name }}-disk0
          name: disk0
{% if boot_iso_pvc_name is defined and boot_iso_pvc_name|length > 0 %}
        - name: boot-iso
          persistentVolumeClaim:
            claimName: {{ boot_iso_pvc_name }}
{% else %}
        - name: cloudinitdisk
          cloudInitNoCloud:
{% if template.networks is defined and template.networks|length > 0 %}
{% set network_data_content %}
{% include 'templates/cloud_init-network.yml.j2' %}
{% endset %}
            networkData: |
{{ network_data_content | indent(14, True) }}
{% endif %}
{% set user_data_content %}
{% include 'templates/cloud_init-user.yml.j2' %}
{% endset %}
            userData: |
{{ user_data_content | indent(14, True) }}
{% endif %}